name: dash-app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dash
  - gsw
  - numpy
  - pandas
  - plotly
  - ipyvolume
  - ipywidgets
  - appmode
  - jupyterlab>=4.4.4
  - jupyterlab-dash
  - plotly::jupyterlab-dash
  - voila

