name: dash-app
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dash
  - gsw
  - numpy
  - pandas
  - plotly
  - ipyvolume
  - appmode
  - jupyterlab
  - jupyterlab-dash
  - jupyterlab-plotly
  - voila
