#!/bin/bash

# Enable nbserverproxy
jupyter server extension enable --sys-prefix nbserverproxy

# Install the bokeh server extension so that Bokeh launches at startup
mv .binder/dashserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/

# Enable Bokeh extension
jupyter server extension enable --sys-prefix dashserverextension

#jupyter lab clean
#jupyter lab build
# python -c "import ipyvolume; ipyvolume.datasets.aquariusA2.fetch()"
