#!/bin/bash

# Enable nbserverproxy
# jupyter server extension enable --sys-prefix nbserverproxy
#echo "Start server proxy"
#pip install jupyter-server-proxy

# Install the dash server extension so that dash launches at startup
echo "Install extension"
mv .binder/dashserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/

# Enable dash extension
echo "Enable extension"
jupyter server extension enable --sys-prefix dashserverextension

#jupyter lab clean
#jupyter lab build
# python -c "import ipyvolume; ipyvolume.datasets.aquariusA2.fetch()"
